### ISSUE TITLE
Error if '--bam' missing

### ISSUE THREAD

**Issue by muppetjones** [zstephens/neat-genreads#9]
Getting an error that I think is due to not using `--bam`.

```
sampling reads...
Traceback (most recent call last):
  File "/neat-genreads/genReads.py", line 637, in <module>
    main()
  File "/neat-genreads/genReads.py", line 585, in main
    myRefIndex = indices_by_refName[bamHeader[0][RI][0]]
TypeError: 'NoneType' object has no attribute '__getitem__'
40.290 (sec)
```

**Comment by zstephens** [comment]
Incidentally I just pushed a fix related to that exact line to the repository a minute ago. Could you pull and try again?

Thanks!
Zach

On Oct 14, 2016, at 2:11 PM, Stephen J Bush <notifications@github.com<mailto:notifications@github.com>> wrote:


Getting an error that I think is due to not using --bam.

sampling reads...
Traceback (most recent call last):
  File "/neat-genreads/genReads.py", line 637, in <module>
    main()
  File "/neat-genreads/genReads.py", line 585, in main
    myRefIndex = indices_by_refName[bamHeader[0][RI][0]]
TypeError: 'NoneType' object has no attribute '__getitem__'
40.290 (sec)
